### ISSUE TITLE
How to use Microsoft E2E Dialogue Challenge dataset 

### ISSUE THREAD

**Issue by zhufangda** [derekchen14/task_oriented_dialog_agent#11]
Hello,
    I would like use Microsoft E2E Dialogue Challenge for training my chatbot. But I meet some trouble when I preprocess this data. Can you share how you did the preprocessing?

Cordialement

**Comment by derekchen14** [comment]
I used a pre-processing script that normalized the data and simplified the outputs.  I will be adding that to the data folder in the future when the pipeline is more stable.  Still working on updating the vocabulary.

**Comment by derekchen14** [comment]
conversion scripts have been added to the scripts folder, still under progress, but this issue will now be closed
